### PR TITLE
Move should override dest files for localfs

### LINKED ISSUE #73: Tests failing after I modified Move/Copy test cases to use variable len payloads
In a previous PR I discovered that sftp/localstore and Azure test cases were failing after I switched test cases to using variable length payloads.  

SFTP/Localstore failed because the files weren't correctly being truncated before being written too.  So, if new data was less than the previous data, then the file will contain extra data and be corrupted. 

Azure turned out to be a race with how we wrote to the backing store.

### PR DESCRIPTION
**Pull request by epsniff**
Closes #73 

Fixes the following issues:

- localfs wasn't correctly truncating the "store" file before moving over it.  The result is that data could get corrupted when it's overwritten.
- adding more tests that deal with variable length data sets, so that we can detect truncation issues.  
- Fix a race condition in azures, such that it wasn't managing a go routine that flushed data to the backing store.
- Performance improvement for the Copy and Move functions.  They now use io Reader/Writers to stream data from a src->des, instead of copying the data to a local file and then uploading that local file to the des.

### CODE REVIEW

File: store.go [hunk 1]
```diff
@@ -280,18 +280,50 @@ func Move(ctx context.Context, s Store, src, des Object) error {
 		}
 	}
 
+	//	// Slow path, copy locally then up to des
```
Comment (epsniff) [inline store.go]: I'm experimenting with doing the move with out using a local intermediate file, TODO remove this if not used before merging the PR.

File: testutils/testutils.go [hunk 2]
```diff
@@ -230,44 +235,73 @@ func createFile(t TestingT, store cloudstorage.Store, name string) cloudstorage.
...
-	deleteIfExists(store, "from/test.csv")
-	deleteIfExists(store, "to/testmove.csv")
-
+	deleteIfExists(store, "to/testmove.txt")
 	switch store.Type() {
 	case "azure":
 		// wtf, eff you azure.
 		time.Sleep(time.Millisecond * 1100)
+	case "sftp":
+		t.Logf("SKIPPING MOVE tests for SFTP")
```
Comment (epsniff) [inline testutils/testutils.go]: Oh, I should remove this and test again....

**Comment by araddon** [comment]
Can you update PR to link/ref/close tickets that this covers?

**Comment by araddon** [comment]
do you mind doing a squash and merge on this pr?
